// File: fnc_laptop_stateVarsExcluded.sqf
#include "..\script_component.hpp"
/*
 * Author: Root, y0014984, Wasserstoff
 * Description: Returns the list of laptop object variables that must NOT be copied when snapshotting
 * or restoring a laptop's state. Excludes variables holding TEXT buffers (which cannot serialize),
 * runtime locks/flags that init regenerates, the live power draw/state, and all CODE references
 * (function handles), which are rebuilt by the device init pass. Shared by the laptop item
 * pack/deploy path and the Zeus Save/Restore Laptop modules so the exclusion set stays consistent.
 *
 * Arguments:
 * None
 *
 * Return Value:
 * Excluded variable names <ARRAY of STRING>
 *
 * Example:
 * private _excluded = call AE3_armaos_fnc_laptop_stateVarsExcluded;
 *
 * Public: No
 */

[
    "AE3_terminal",                 // HashMap containing TEXT in AE3_terminalRenderedBuffer - causes serialization warnings
    "AE3_terminalRenderedBuffer",  // Contains TEXT - will be regenerated locally
    "AE3_terminalDialog",           // Display reference - not serializable
    "AE3_Links",                    // Command links - will be regenerated by fnc_link_init
    "AE3_computer_mutex",           // Runtime lock - should not persist
    "AE3_desktop_sessionUser",      // Live GUI session - a clone must start signed out, not inherit a session
    "AE3_desktop_sessionOwner",     // Live GUI session owner UID - see above
    "AE3_laptop_restored",          // Restoration flag - only used during deployment, don't save
    "AE3_UiOnTexActive",            // Runtime UI-on-Texture flag - texture must be re-set on deploy
    "AE3_UiOnTexDisplayName",       // Runtime UI-on-Texture display name - will be regenerated on deploy
    "AE3_interaction_hasEquipmentAction",  // Runtime ACE interaction flag - will be re-added by init
    "AE3_interaction_laptopActionsAdded",  // Runtime flag - will be re-added by init
    "AE3_interaction_equipmentActionsAdded",  // Runtime flag - will be re-added by init
    "AE3_power_actionsAdded",       // Runtime flag - will be re-added by init
    "AE3_power_powerState",         // Power state - never copy, leave the target's own state alone
    "AE3_power_powerDraw",          // Runtime power draw - will be recalculated
    // All CODE references must be excluded - they cannot serialize and will be regenerated by init
    "AE3_interaction_fnc_open",
    "AE3_interaction_fnc_close",
    "AE3_interaction_fnc_openWrapper",
    "AE3_interaction_fnc_closeWrapper",
    "AE3_interaction_fnc_openActionCondition",
    "AE3_interaction_fnc_closeActionCondition",
    "AE3_power_fnc_turnOn",
    "AE3_power_fnc_turnOff",
    "AE3_power_fnc_standby",
    "AE3_power_fnc_turnOnWrapper",
    "AE3_power_fnc_turnOffWrapper",
    "AE3_power_fnc_standbyWrapper",
    "AE3_power_fnc_turnOnCondition",
    "AE3_power_fnc_turnOffCondition",
    "AE3_power_fnc_standbyCondition"
]
